apiVersion: v1
kind: Pod
metadata:
  name: get-acr-digest-keyless-with-oidc
spec:
  serviceAccountName: default
  containers:
    - args:
        - <REPO>
      image: mozillazg/get-acr-digest:0.1.0
      imagePullPolicy: Always
      name: get-acr-digest
      env:
        - name: ALIBABA_CLOUD_OIDC_TOKEN_FILE
          value: /var/run/secrets/tokens/rrsa-oidc-token
        - name: ALIBABA_CLOUD_ROLE_ARN
          value: <ROLE_ARN>
        - name: ALIBABA_CLOUD_OIDC_PROVIDER_ARN
          value: <OIDC_PROVIDER_ARN>
      resources:
        limits:
          cpu: 100m
          memory: 10Mi
        requests:
          cpu: 100m
          memory: 10Mi
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: rrsa-oidc-token
          readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
    - name: rrsa-oidc-token
      projected:
        sources:
          - serviceAccountToken:
              path: rrsa-oidc-token
              expirationSeconds: 7200
              audience: "sts.aliyuncs.com"
