name: Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.41

  releaser-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
        env:
          GOPATH: ${{ env.HOME }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --skip=publish
        env:
          GOPATH: ${{ env.HOME }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26", "1.27"]
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOPATH: ${{ env.HOME }}

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test pkg/acr
        run: cd pkg/acr && go test -v ./...
